BQ5K:
  cohortTableHandler:
    database:
      databaseId: BQ5K
      databaseName: bigquery5k
      databaseDescription: BigQuery database
    connection:
      connectionDetailsSettings:
          dbms: bigquery
          drv: bigrquery::bigquery()
          project: atlas-development-270609
          billing: atlas-development-270609
          bigint: integer64
      tempEmulationSchema: atlas-development-270609.sandbox
    cdm:
        cdmDatabaseSchema: atlas-development-270609.finngen_omop_r13_v3_5k
        vocabularyDatabaseSchema: atlas-development-270609.finngen_omop_r13_v3_5k
        resultsDatabaseSchema: atlas-development-270609.finngen_omop_result_r13_v3_5k
# AtlasDevelopment-full
BQ5:
  cohortTableHandler:
    database:
      databaseId: BQ
      databaseName: bigquery
      databaseDescription: BigQuery database with 500k patients
    connection:
      connectionDetailsSettings:
          dbms: bigquery
          drv: bigrquery::bigquery()
          project: atlas-development-270609
          billing: atlas-development-270609
          bigint: integer64
      tempEmulationSchema: atlas-development-270609.sandbox
    cdm:
        cdmDatabaseSchema: atlas-development-270609.finngen_omop_r13_v3
        vocabularyDatabaseSchema: atlas-development-270609.finngen_omop_r13_v3
        resultsDatabaseSchema: atlas-development-270609.finngen_omop_result_r13_v3
DF13:
  cohortTableHandler:
    database:
      databaseId: DF13
      databaseName: FinnGen DF13
      databaseDescription: FinnGen database 13
    connection:
      connectionDetailsSettings:
        dbms: bigquery
        drv: bigrquery::bigquery()
        project: <sandboxProject>
        billing: <sandboxProject>
        bigint: integer64
      tempEmulationSchema: <sandboxProject>.sandbox #needed for creating tmp table in BigQuery
    cdm:
      cdmDatabaseSchema: finngen-production-library.finngen_omop_r13_v3
      vocabularyDatabaseSchema: finngen-production-library.finngen_omop_r13_v3
      resultsDatabaseSchema: finngen-production-library.finngen_omop_result_r13_v3
DF13test:
  cohortTableHandler:
    database:
      databaseId: DF13test
      databaseName: FinnGen DF13test
      databaseDescription: FinnGen database 13
    connection:
      connectionDetailsSettings:
        dbms: bigquery
        drv: bigrquery::bigquery()
        project: <sandboxProject>
        billing: <sandboxProject>
        bigint: integer64
      tempEmulationSchema: <sandboxProject>.sandbox #needed for creating tmp table in BigQuery
    cdm:
      cdmDatabaseSchema: finngen-production-library.finngen_omop_r13_v3
      vocabularyDatabaseSchema: finngen-production-library.finngen_omop_r13_v3
      resultsDatabaseSchema: <sandboxProject>.sandbox
